language: java
jdk:
- oraclejdk8

# force upgrade Java8 as per https://github.com/travis-ci/travis-ci/issues/4042 (fixes compilation issue)
addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false
# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
env:
  global:
  - secure: KXXnepYrIN5l0ExDhAbxd1LgRx12Qb7IdSGTYdNiWw5NCEymtxs8Ll1y9NwGpz4EbJ4NufNwS5tKM78yy5wkVompNQy5mnKgd+JCRMMHqMU5LKcZEQnqUqqdaecUQn5UUJuLZuNwpx+DDbosFUpESAjFP2g09HQUpX59CCyymv9UkN6wVyVYvFJpQq7Sm4aaNXDh3c95VsRdYwVFfhucYzCMtz+af+WT/Z0X91TQBdVCLtQdezVYlwoEMeVP8Q7+WZcrB2Zm6b2LdIv1TzZT/0COZ432pSI2iOqDqolBZbxYCf9Tdx0Q7fEpqpnN1HFPgo2g7mGhDhjmJ3QVatcgRSa2Xa8aV1uGnr9BTsLmyk/yAY6ksDTjBpAOEp+hslCujm7aFGZpWf8p3QHNquE+hxeBdHab7Q4O+tlf51wkydPcgdm+e7XXxxTx4Lq3CMGCUFjUN0NOucT7cnndKZGh+JPocJJYLYg+SFT2W78ppeCBPTod19il7Hq0r5iOoraWtnzn/OUh8ChHPdO+Yp994Zff7IDoSHD4s/Tq9EHoq8iVgf2Gtq/FoVrH3Mqy6mwtruvLABx1C0ephxIBpQ5PYl0bSu34p2Epus6kW4YHy4H3F1ltMURCUxlGb0GLU1TGLBOIGJERGXqDI7YglfySY5dc22Cp4Cby+GVgXXgIb5g=
  - secure: OaCI4AEtFlHyOuJ9AfdaAnSCPN7MmU4T0Id7kfa1lN4w4mKb5fgz/DAhNeCfJ5liTq+5Jbv+LZefr/rDUEY25zuEdBsVae6xC/bZiubAjJRhwDZEVNX8Pnk0UXzAutvjPrzqePoigBP6UDiG9yFu3RDSZg/OMCTVszJSMGQTZrWtJPlw0Aiq+DLbpsSUCuBIlhWI9D2G2dZHrd4ut2MQBL41efvFTujxVDklLbzW0PGBHsaI+9DIsEaLQ847v67yndA8sxujhUcIy3PXdW+cKK2t0HvOVe6/+eKeYFl+qWmlm2rbbMHNifqy/Hy0p8T0cUqo9rqMQTnXM9E2kzSDWhsWeU9B3y03+zdG/AQE0+B5HaGZ7MMYSqsfx6FhmHzSidodCNcwrhUOFwqdquJT1fEjpRGyyNzc09CP5DmJRc1L1vb38lIy1aocYofHapE4uWJJr8A1Rymrb2RmEwyhet6byAUGf6W6qGUHaa4aYE2FeCYycMb8QGwrG15pMTIEkK45X2DH4Tc+ZM73DJ1cW2/CTtFoLx+2NSzXqjVmF30U/jqBZSWw2MbzR5PKR8/B3b6xn22v7DGWyQXa9GhjME+5tRc7LrDIxHpvGGNqivzVmgkE/PXezEuc0/Y61FMR4CdyuGiwU8XfLr9sKModtl/ON8v5e+4BxN8sFfiGgng=
